"""Application constants."""

# QML Registration
QML_IMPORT_NAME = "DBToolkit"
QML_IMPORT_MAJOR_VERSION = 1

# Cache Settings
DEFAULT_CACHE_TTL = 300  # 5 minutes

# UI Constants
DEFAULT_WINDOW_WIDTH = 1200
DEFAULT_WINDOW_HEIGHT = 800
CONNECTION_PANEL_WIDTH = 300
SCHEMA_PANEL_WIDTH = 350

# Database Connection Timeouts
DEFAULT_CONNECTION_TIMEOUT = 30
DEFAULT_QUERY_TIMEOUT = 60